### ISSUE TITLE
ESLint Gulp implementation

### ISSUE THREAD

**Issue by IstiaqueSiddiqi** [google-udacity-india-scholars/mws-track-gifs#13]

**Comment by CDharmateja** [comment]
I would like to work on this issue. Can you please describe all the things I need to implement? And the prod directory should be automatically generated by gulp, So I think there's no need to put prod folder in this repo.

**Comment by CDharmateja** [comment]
Until design is ready(#7 ), We need to code some basic website that describes this project so that we can work on this issue and service worker implementation(#12 ).

**Comment by IstiaqueSiddiqi** [comment]
Hi @CDharmateja ,

Thanks for showing your interest. Yes, that's correct gulp will create the folder but I did that intentionally so that others can understand the project structure. Right now you can setup ESLint in gulp #13. Before starting please create the branch from develop branch. And try to follow https://udacity.github.io/git-styleguide/

**Comment by IstiaqueSiddiqi** [comment]
This issue has been implemented #18
