### ISSUE TITLE
Project Discussion: Gify

### ISSUE THREAD

**Issue by IstiaqueSiddiqi** [google-udacity-india-scholars/mws-track-gifs#17]
### About Project:

Idea is to build PWA that shows all trending animated gifs on home page and under favorite section save all your favorite gifs and under categories section we will be listing all the different gif category like happy, sad, wedding, greetings, etc and under each category we will have different gifs for that particular category. One can even search any kind of gif for any given word, user has the option to share the gif with others. And the app works in offline mode.

We'll be using open source GIPHY API that return different kind of gifs. One needs to get their respective own developer key from [ https://giphy.com/](url) by registering.

To know more about on getting started go though [readme](https://github.com/google-udacity-india-scholars/mws-track-gifs/blob/develop/README.md) file.

For contribution do checkout open [TODOs](https://github.com/google-udacity-india-scholars/mws-track-gifs/projects/1) or else can reach out to @IstiaqueSiddiqi before working on their own created issue;

### Mockup:

![img_20181016_175225](https://user-images.githubusercontent.com/14907304/47086443-1dcfec00-d237-11e8-84f0-380c7118a1c6.jpg)

**Comment by IstiaqueSiddiqi** [comment]
**Here we can brainstorm and discuss about project**

**Comment by IstiaqueSiddiqi** [comment]
Hi @CDharmateja ,

I have added few other functionality. Added snackbar for online and offline event, layout for categories section with different categories. Yet this not responsive. Do have a look at it.

**Comment by CDharmateja** [comment]
Nice work @IstiaqueSiddiqi ! But I find a few issues with the code. The js files have eslint errors. In dbhelper.js, I get an error `url undefined` in line 32.

**Comment by IstiaqueSiddiqi** [comment]
> Nice work @IstiaqueSiddiqi ! But I find a few issues with the code. The js files have eslint errors. In dbhelper.js, I get an error `url undefined` in line 32.

Thanks pointing out that missed to pass url to method. Will fix it.
