### ISSUE TITLE
Adding a Contributing.md file

### ISSUE THREAD

**Issue by Abdulkadir98** [google-udacity-india-scholars/mws-track-gifs#29]
A separate file for how to contribute will make the process clear to anyone who wishes to contribute.

**Comment by IstiaqueSiddiqi** [comment]
Good idea @Abdulkadir98. Once you are done raise a PR for it.

**Comment by Abdulkadir98** [comment]
Sure, thanks!

**Comment by Abdulkadir98** [comment]
Hello, @IstiaqueSiddiqi I just submitted a PR please check it out.
