### ISSUE TITLE
Adding accessibility to the app.

### ISSUE THREAD

**Issue by IstiaqueSiddiqi** [google-udacity-india-scholars/mws-track-gifs#45]
Thanks @sourybunny for coming forward and taking this up. Really appreciate your enthusiasm.

**Comment by imvpn22** [comment]
I want to work on this.

**Comment by IstiaqueSiddiqi** [comment]
@imvpn22  @sourybunny is working on it and hope will be getting PR soon.

I have suggested some other task to you on slack if you feel like can work on it.

Thanks

**Comment by sourybunny** [comment]
@IstiaqueSiddiqi I have completed it almost. Will be making a  PR soon.

**Comment by IstiaqueSiddiqi** [comment]
@sourybunny has implemented this.
