### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by IstiaqueSiddiqi** [google-udacity-india-scholars/mws-track-gifs#9]

**Comment by CDharmateja** [comment]
The navigation bar of the landing page isn't responsive

**Comment by IstiaqueSiddiqi** [comment]
Yes, it is not responsive yet. Right now I doing some basic setup...There is already listed task for responsive and other issues.

Have a look at it.
https://github.com/google-udacity-india-scholars/mws-track-gifs/projects/1
